"use client";

// LOCKED: confirmed by the user. Do not edit this file without asking the user first.

import { useEffect, useId, useRef, useState } from "react";
import { IconTile } from "./icons";
import { SmartLink } from "./smart-link";

type Card = { title: string; description: string; href?: string; fit?: string; problems?: string; outcomes?: string };

const lines = (s?: string) =>
  (s ?? "")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);

// The sub-services of a service page ("What we build") in ONE line. On a desktop it is a strip of panels: the one that is open is wide and
// shows everything, the others are slim with their icon and a vertical title. Under the strip is the detail of the open panel: when it is the
// right choice, which problems it solves and what you get. When the cards have those points the strip is pinned and the PAGE SCROLL drives
// it: the panels open one after the other and, inside each panel, its points light up one by one. Hover (when it is not pinned), focus or a
// click opens a panel too. On a tablet or a phone it is a single swipeable row of full cards with the points inside each card.
// Every panel has a real button (aria-expanded), closed panels are out of the tab order, focus rings are visible, and nothing is pinned or
// animated for visitors who prefer less motion.
export function ServiceStrip({ cards }: { cards: Card[] }) {
  const [active, setActive] = useState(0);
  const [step, setStep] = useState(99); // how many points of the open panel are lit (99 = all)
  const uid = useId();
  const trackRef = useRef<HTMLDivElement>(null);
  const stickyRef = useRef<HTMLDivElement>(null);
  const barRef = useRef<HTMLSpanElement>(null);
  const manual = useRef(false);
  const pinned = useRef(false);
  const kRef = useRef<number[]>([]);
  const n = cards.length;
  const data = cards.map((c) => ({ fit: (c.fit ?? "").trim(), problems: lines(c.problems), outcomes: lines(c.outcomes) }));
  const hasDetail = data.some((d) => d.fit || d.problems.length || d.outcomes.length);
  const cur = data[active] ?? data[0];
  const plainTitle = (i: number) => (cards[i]?.title ?? "").replace(/\s*\n\s*/g, " ");

  useEffect(() => {
    kRef.current = data.map((d) => (d.fit ? 1 : 0) + d.problems.length + d.outcomes.length);
  });

  const pick = (i: number) => {
    manual.current = true;
    setActive(i);
    setStep(99);
  };

  // On a desktop the strip is pinned while the page scrolls and the scroll opens the panels one after the other, lighting up their points.
  useEffect(() => {
    const track = trackRef.current;
    const sticky = stickyRef.current;
    if (!track || !sticky || !hasDetail) return;
    const mq = window.matchMedia("(min-width: 1024px) and (prefers-reduced-motion: no-preference)");
    let raf = 0;
    let lastIdx = -1;
    let lastStep = -1;
    const tick = () => {
      raf = 0;
      pinned.current = mq.matches;
      if (!mq.matches) return;
      const r = track.getBoundingClientRect();
      const top = parseFloat(getComputedStyle(sticky).top) || 0;
      const dist = Math.max(1, r.height - sticky.offsetHeight);
      const p = Math.min(1, Math.max(0, (top - r.top) / dist));
      if (barRef.current) barRef.current.style.transform = `scaleX(${p.toFixed(3)})`;
      const idx = Math.min(n - 1, Math.floor(p * n));
      const q = Math.min(1, p * n - idx);
      if (idx !== lastIdx) {
        lastIdx = idx;
        lastStep = -1;
        manual.current = false;
        setActive(idx);
      }
      if (!manual.current) {
        const k = Math.max(1, kRef.current[idx] ?? 1);
        const s = Math.min(k, Math.floor(Math.min(1, q / 0.8) * k) + 1);
        if (s !== lastStep) {
          lastStep = s;
          setStep(s);
        }
      }
    };
    const schedule = () => {
      if (!raf) raf = requestAnimationFrame(tick);
    };
    schedule();
    window.addEventListener("scroll", schedule, { passive: true });
    window.addEventListener("resize", schedule);
    return () => {
      window.removeEventListener("scroll", schedule);
      window.removeEventListener("resize", schedule);
      if (raf) cancelAnimationFrame(raf);
    };
  }, [n, hasDetail]);

  // the order in which the points of the open panel light up: the sentence first, then the problems, then what you get
  const fitAt = 0;
  const problemAt = (j: number) => (cur.fit ? 1 : 0) + j;
  const outcomeAt = (j: number) => (cur.fit ? 1 : 0) + cur.problems.length + j;

  return (
    <div ref={trackRef} className="ss-track" data-pin={hasDetail} style={{ "--n": n } as React.CSSProperties}>
      <div ref={stickyRef} className="ss-sticky">
        <div className="ss-wrap">
          <ul className="ss">
            {cards.map((card, i) => {
              const open = active === i;
              const id = `${uid}-${i}`;
              const d = data[i];
              return (
                <li key={i} className="ss-p card-glass" data-active={open} style={{ "--k": i } as React.CSSProperties} onMouseEnter={() => !pinned.current && pick(i)}>
                  <button type="button" className="ss-hit" aria-expanded={open} aria-controls={id} onClick={() => pick(i)} onFocus={() => pick(i)}>
                    <span className="sr-only">{plainTitle(i)}</span>
                  </button>
                  <div className="ss-glow" aria-hidden />
                  <span className="ss-big" aria-hidden>
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  {/* the slim version (desktop only) */}
                  <div className="ss-slim" aria-hidden>
                    <span className="ss-no">{String(i + 1).padStart(2, "0")}</span>
                    <IconTile index={i} />
                    <span className="ss-vt">{plainTitle(i)}</span>
                  </div>
                  {/* the full version */}
                  <article id={id} className="ss-full">
                    <IconTile index={i} large />
                    <h3 className="ss-title">{card.title}</h3>
                    <p className="ss-text">{card.description}</p>
                    {/* tablet and phone: the points live inside the card */}
                    {(d.fit || d.problems.length > 0 || d.outcomes.length > 0) && (
                      <div className="ss-info">
                        {d.fit && (
                          <p className="ss-i-fit">
                            <b>Right for you when</b>
                            {d.fit}
                          </p>
                        )}
                        {d.problems.length > 0 && (
                          <div>
                            <b>Problems it solves</b>
                            <ul>
                              {d.problems.map((t, j) => (
                                <li key={j}>{t}</li>
                              ))}
                            </ul>
                          </div>
                        )}
                        {d.outcomes.length > 0 && (
                          <div>
                            <b className="ss-good">What you get</b>
                            <ul className="ss-ok">
                              {d.outcomes.map((t, j) => (
                                <li key={j}>{t}</li>
                              ))}
                            </ul>
                          </div>
                        )}
                      </div>
                    )}
                    {card.href && (
                      <SmartLink href={card.href} className="ss-more">
                        Learn more
                        <svg viewBox="0 0 24 24" className="size-4 fill-none stroke-current" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                          <path d="M5 12h14M13 6l6 6-6 6" />
                        </svg>
                      </SmartLink>
                    )}
                  </article>
                </li>
              );
            })}
          </ul>

          {/* desktop: the detail of the open panel; its points light up with the scroll */}
          {hasDetail && (
            <div className="ss-detail card-glass" role="region" aria-label={`${plainTitle(active)}: when to choose it, the problems it solves and what you get`}>
              <div key={active} className="ss-d-in">
                <p className="ss-d-for">
                  <span>{String(active + 1).padStart(2, "0")}</span>
                  {plainTitle(active)}
                </p>
                <div className="ss-d-col">
                  <b className="ss-d-label">Right for you when</b>
                  {cur.fit && (
                    <p className="ss-d-fit" data-on={step > fitAt} data-now={step === fitAt + 1}>
                      {cur.fit}
                    </p>
                  )}
                </div>
                <div className="ss-d-col">
                  <b className="ss-d-label">Problems it solves</b>
                  <ul>
                    {cur.problems.map((t, j) => (
                      <li key={j} data-on={step > problemAt(j)} data-now={step === problemAt(j) + 1}>
                        {t}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="ss-d-col">
                  <b className="ss-d-label ss-good">What you get</b>
                  <ul className="ss-ok">
                    {cur.outcomes.map((t, j) => (
                      <li key={j} data-on={step > outcomeAt(j)} data-now={step === outcomeAt(j) + 1}>
                        {t}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          )}

          <p className="ss-hint" aria-hidden>
            <span>Swipe</span>
            <svg viewBox="0 0 24 24" className="size-4 fill-none stroke-current" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M5 12h14M13 6l6 6-6 6" />
            </svg>
          </p>
          <div className="ss-prog" aria-hidden>
            <span className="ss-prog-n">
              {String(active + 1).padStart(2, "0")} / {String(n).padStart(2, "0")}
            </span>
            <span className="ss-prog-bar">
              <span ref={barRef} />
            </span>
            <span className="ss-prog-t">Scroll to explore</span>
          </div>
        </div>
      </div>
    </div>
  );
}
