import type { Field } from "./fields";
import { GOV_PROJECTS, GOV_TITLE } from "./content/gov-projects";
import { DEVICES, QUIZ } from "./content/metaverse-extra";
import { TEAM_MEMBERS } from "./content/team";

// Every section a page can contain. Adding a new section = add an entry here + a component in
// src/components/site/sections/ + one line in that folder's index.tsx. The admin editor picks it up automatically.
// `defaults` only describe the data shape (and fill in keys that are missing from old saved data);
// the real home page content lives in ./content/home.ts.

function defineSection<D extends Record<string, unknown>>(def: { label: string; description: string; fields: Field[]; defaults: D }) {
  return def;
}

const HIGHLIGHT_HINT = "Tip: put *stars* around words to highlight them.";
const LINES_HINT = "Press Enter to start the second line (the lower line is brighter).";

const chip = (hint?: string): Field => ({ kind: "text", key: "chip", label: "Small label above the heading", max: 40, hint });
const headingField = (label = "Heading"): Field => ({ kind: "textarea", key: "heading", label, max: 120, hint: LINES_HINT });

export const SECTIONS = {
  hero: defineSection({
    label: "Hero scene (ball + service cards)",
    description: "One pinned screen: a glowing ball that breaks into particles while you scroll, then glass cards",
    fields: [
      { kind: "text", key: "title", label: "Page heading (not shown on screen)", max: 160, hint: "Read by Google and screen readers only. Put your brand and main keywords here." },
      { kind: "text", key: "mark", label: "Character inside the glowing ball", max: 3, hint: "Shown in the middle of the ball, e.g. 7" },
      { kind: "text", key: "above", label: "Text above the ball", max: 30, hint: "Made of particles, e.g. Celebrating (leave empty for none)" },
      { kind: "text", key: "below", label: "Text below the ball", max: 30, hint: "Made of particles, e.g. Years of We3vision (leave empty for none)" },
      {
        kind: "list",
        key: "cards",
        label: "Service boxes (a small row at the top; pointing at one opens its sub-services)",
        itemLabel: "Service",
        max: 8,
        fields: [
          { kind: "textarea", key: "title", label: "Name", max: 60, hint: "Press Enter to start a second line inside the small box." },
          { kind: "url", key: "href", label: "Link to the service page (leave empty for no link)" },
          { kind: "textarea", key: "summary", label: "One sentence about the service (shown when it is open)", max: 200, hint: "Plain words with your main keywords, so visitors and Google understand what the service is." },
          {
            kind: "textarea",
            key: "subs",
            label: "Sub-services: one per line as  Name | short description | page link  (up to 4 are shown)",
            max: 1100,
            hint: "The page link is optional. Example: Logo design | A logo that fits your business. | /brand-identity/logo-design",
          },
        ],
      },
    ],
    defaults: { title: "Brand: main keywords", mark: "7", above: "", below: "", cards: [{ title: "Service\nname", href: "", summary: "One sentence about this service.", subs: "Sub-service one | What you get from it\nSub-service two | What you get from it" }] },
  }),
  story: defineSection({
    label: "Story",
    description: "Large paragraph text with highlighted phrases",
    fields: [{ kind: "textarea", key: "body", label: "Text", max: 3000, hint: `${HIGHLIGHT_HINT} Leave an empty line between paragraphs.` }],
    defaults: { body: "Text with *highlighted words*." },
  }),
  brandBoard: defineSection({
    label: "Brand board (text + live brand board)",
    description: "A wide two-column intro: a brand board that lights up tile by tile on the left, a large sentence that fills with light while you scroll and a list of what is included on the right.",
    fields: [
      chip(),
      { kind: "textarea", key: "lead", label: "Large sentence (fills with light while scrolling)", max: 220, hint: HIGHLIGHT_HINT },
      { kind: "textarea", key: "body", label: "Paragraph under it", max: 700, hint: HIGHLIGHT_HINT },
      { kind: "text", key: "listIntro", label: "Words above the list", max: 60, hint: "e.g. Our branding service can include" },
      { kind: "textarea", key: "points", label: "List: one per line as  Name | short description  (the five lines belong to the five boxes of the board)", max: 700, hint: "Example: Logo design | A logo, colours and typography that fit your business." },
      { kind: "text", key: "ctaLabel", label: "Button at the end of the list (leave empty for none)", max: 40 },
      { kind: "url", key: "ctaHref", label: "Button link", hint: "e.g. #contact" },
      { kind: "text", key: "note", label: "Small note next to the button", max: 100, hint: "e.g. depending on what your project needs" },
    ],
    defaults: { chip: "About the service", lead: "A *strong brand* gives your business a consistent look.", body: "Short paragraph.", listIntro: "It can include", points: "Point one | What it is\nPoint two | What it is", ctaLabel: "", ctaHref: "#contact", note: "" },
  }),
  strengths: defineSection({
    label: "Strengths",
    description: "Heading and large cards with an illustration",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Cards (the first one is shown wide)",
        itemLabel: "Card",
        max: 3,
        fields: [
          { kind: "textarea", key: "title", label: "Title", max: 80, hint: LINES_HINT },
          { kind: "textarea", key: "description", label: "Description", max: 360 },
        ],
      },
    ],
    defaults: { chip: "Strengths", heading: "Heading\nsecond line", intro: "Intro.", items: [{ title: "Title\nsecond line", description: "Description." }] },
  }),
  services: defineSection({
    label: "Services",
    description: "Heading and a grid of service cards",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      { kind: "text", key: "buttonLabel", label: "Button text", max: 30 },
      { kind: "url", key: "buttonHref", label: "Button link" },
      {
        kind: "list",
        key: "cards",
        label: "Cards",
        itemLabel: "Card",
        max: 12,
        fields: [
          { kind: "textarea", key: "title", label: "Title", max: 60, hint: LINES_HINT },
          { kind: "textarea", key: "description", label: "Description", max: 260 },
          { kind: "url", key: "href", label: "Link to the service page (leave empty to hide)" },
          { kind: "textarea", key: "fit", label: "When is it the right choice? (one sentence, optional)", max: 220 },
          { kind: "textarea", key: "problems", label: "Problems it solves (one per line, optional)", max: 400, hint: "One point per line: press Enter for the next one." },
          { kind: "textarea", key: "outcomes", label: "What you get (one per line, optional)", max: 400, hint: "One point per line: press Enter for the next one." },
        ],
      },
    ],
    defaults: {
      chip: "Services",
      heading: "Heading\nsecond line",
      intro: "Intro.",
      buttonLabel: "Contact Us",
      buttonHref: "#contact",
      cards: [{ title: "Service\nname", description: "Description.", href: "" }],
    },
  }),
  highlights: defineSection({
    label: "Highlights",
    description: "Big numbers with a label",
    fields: [
      chip(),
      {
        kind: "list",
        key: "items",
        label: "Numbers",
        itemLabel: "Number",
        max: 6,
        fields: [
          { kind: "text", key: "value", label: "Number", max: 12 },
          { kind: "text", key: "label", label: "Label", max: 40 },
        ],
      },
    ],
    defaults: { chip: "Highlights", items: [{ value: "10+", label: "Label" }] },
  }),
  industries: defineSection({
    label: "Industries",
    description: "Tabs of industries; picking one shows its description",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Industries",
        itemLabel: "Industry",
        max: 12,
        fields: [
          { kind: "text", key: "name", label: "Industry", max: 60 },
          { kind: "textarea", key: "description", label: "Description", max: 700 },
        ],
      },
    ],
    defaults: { chip: "Industries", heading: "Heading\nsecond line", intro: "", items: [{ name: "Industry", description: "Description." }] },
  }),
  advantages: defineSection({
    label: "Advantages",
    description: "Heading and a 2-column list of benefits",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Benefits",
        itemLabel: "Benefit",
        max: 8,
        fields: [
          { kind: "text", key: "title", label: "Title", max: 60 },
          { kind: "textarea", key: "description", label: "Description", max: 260 },
        ],
      },
    ],
    defaults: { chip: "Advantages", heading: "Heading\nsecond line", intro: "", items: [{ title: "Benefit", description: "Description." }] },
  }),
  blogs: defineSection({
    label: "Blog cards",
    description: "Heading with a 'view all' button and blog post cards",
    fields: [
      chip(),
      headingField(),
      { kind: "text", key: "buttonLabel", label: "Button text", max: 30 },
      { kind: "url", key: "buttonHref", label: "Button link" },
      {
        kind: "list",
        key: "items",
        label: "Blog posts",
        itemLabel: "Post",
        max: 6,
        fields: [
          { kind: "text", key: "category", label: "Category label", max: 30 },
          { kind: "text", key: "title", label: "Title", max: 140 },
          { kind: "image", key: "image", label: "Image", hint: "Image path or link, e.g. /images/blog/post.webp" },
          { kind: "url", key: "href", label: "Link" },
        ],
      },
    ],
    defaults: {
      chip: "Blog",
      heading: "Heading\nsecond line",
      buttonLabel: "View all",
      buttonHref: "/blog",
      items: [{ category: "Category", title: "Post title", image: "", href: "/blog" }],
    },
  }),
  reach: defineSection({
    label: "Global reach",
    description: "Card with text and a rotating globe that marks your offices",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "text", label: "Text", max: 360 },
      { kind: "text", key: "buttonLabel", label: "Button text", max: 30 },
      { kind: "url", key: "buttonHref", label: "Button link" },
      {
        kind: "list",
        key: "places",
        label: "Places marked on the globe (first two are joined by a line)",
        itemLabel: "Place",
        max: 6,
        fields: [
          { kind: "text", key: "label", label: "Name", max: 40 },
          { kind: "text", key: "lat", label: "Latitude", max: 10, hint: "e.g. 21.1702 (north is positive)" },
          { kind: "text", key: "lng", label: "Longitude", max: 10, hint: "e.g. 72.8311 (east is positive)" },
        ],
      },
    ],
    defaults: {
      chip: "Global Reach",
      heading: "Heading\nsecond line",
      text: "Text.",
      buttonLabel: "Contact Us",
      buttonHref: "#contact",
      places: [{ label: "Place", lat: "0", lng: "0" }],
    },
  }),
  contact: defineSection({
    label: "Contact form",
    description: "Heading, enquiry form (saved in Leads) and your contact cards",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "text", label: "Text", max: 360 },
      { kind: "text", key: "buttonLabel", label: "Submit button text", max: 30 },
    ],
    defaults: { chip: "Contact", heading: "Let's Get Started!", text: "Text.", buttonLabel: "Send a Message" },
  }),
  flow: defineSection({
    label: "Diagram: tools → AI → actions",
    description: "A circuit-style picture: boxes on top (where your data lives), a glowing core in the middle, boxes below (what it does). Wires draw themselves and light pulses flow.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 360 },
      { kind: "text", key: "sourcesLabel", label: "Top row title", max: 24, hint: "e.g. Sources" },
      { kind: "text", key: "sourcesNote", label: "Top row note (right side)", max: 30, hint: "e.g. 06 connected" },
      {
        kind: "list",
        key: "sources",
        label: "Top row boxes (6 fit best)",
        itemLabel: "Box",
        max: 6,
        fields: [
          { kind: "text", key: "label", label: "Name", max: 26 },
          { kind: "text", key: "icon", label: "Icon", max: 12, hint: "globe, chat, mail, database, doc, image, users, cart, chart, shield, bolt, bell, gear, calendar, search, spark" },
        ],
      },
      { kind: "text", key: "coreLabel", label: "Core (middle) text", max: 30, hint: "e.g. WE3VISION AI" },
      { kind: "text", key: "actionsLabel", label: "Bottom row title", max: 24, hint: "e.g. Actions" },
      { kind: "text", key: "actionsNote", label: "Bottom row note (right side)", max: 30, hint: "e.g. 06 automations" },
      {
        kind: "list",
        key: "actions",
        label: "Bottom row boxes (6 fit best)",
        itemLabel: "Box",
        max: 6,
        fields: [
          { kind: "text", key: "label", label: "Name", max: 26 },
          { kind: "text", key: "icon", label: "Icon", max: 12, hint: "same names as above" },
        ],
      },
    ],
    defaults: {
      chip: "How it works",
      heading: "From your data\nto real actions",
      intro: "",
      sourcesLabel: "Sources",
      sourcesNote: "06 connected",
      sources: [{ label: "Source", icon: "database" }],
      coreLabel: "AI CORE",
      actionsLabel: "Actions",
      actionsNote: "06 automations",
      actions: [{ label: "Action", icon: "bolt" }],
    },
  }),
  automate: defineSection({
    label: "Switches: by hand → automated",
    description: "A list of problems; each row has a switch that flips by itself when it scrolls into view, and the solution lights up. Visitors can flip the switches too.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      { kind: "text", key: "beforeLabel", label: "Left column title", max: 30, hint: "e.g. Today: by hand" },
      { kind: "text", key: "afterLabel", label: "Right column title", max: 30, hint: "e.g. With AI" },
      { kind: "text", key: "doneLabel", label: "Word after the counter", max: 20, hint: "e.g. automated" },
      {
        kind: "list",
        key: "items",
        label: "Rows (up to 8)",
        itemLabel: "Row",
        max: 8,
        fields: [
          { kind: "text", key: "icon", label: "Icon", max: 12, hint: "globe, chat, mail, database, doc, image, users, cart, chart, shield, bolt, bell, gear, calendar, search, spark" },
          { kind: "text", key: "problem", label: "The problem (left)", max: 70 },
          { kind: "textarea", key: "solution", label: "What AI does (right)", max: 200 },
        ],
      },
    ],
    defaults: {
      chip: "What AI can automate",
      heading: "Problems AI can\ntake off your plate",
      intro: "",
      beforeLabel: "Today: by hand",
      afterLabel: "With AI",
      doneLabel: "automated",
      items: [{ icon: "bolt", problem: "A slow manual task", solution: "How AI does it for you." }],
    },
  }),
  faq: defineSection({
    label: "Questions & answers",
    description: "Frequently asked questions: one answer open at a time (also helps Google show your answers)",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Questions",
        itemLabel: "Question",
        max: 12,
        fields: [
          { kind: "text", key: "question", label: "Question", max: 140 },
          { kind: "textarea", key: "answer", label: "Answer", max: 600 },
        ],
      },
    ],
    defaults: { chip: "FAQ", heading: "Questions\nwe often hear", intro: "", items: [{ question: "Question?", answer: "Answer." }] },
  }),
  archGallery: defineSection({
    label: "Project photos: sliding arches",
    description: "A row of tall arch-shaped photos that slides by itself (pauses when pointed at). For photos of your own client work.",
    fields: [
      {
        kind: "list",
        key: "items",
        label: "Photos",
        itemLabel: "Photo",
        max: 40,
        fields: [
          { kind: "image", key: "image", label: "Photo", hint: "Upload the photo here. Empty = a soft colour placeholder." },
          { kind: "text", key: "title", label: "Project name", max: 60, hint: "Shown when the photo opens on hover." },
          { kind: "text", key: "category", label: "What we did (small label)", max: 40, hint: "e.g. Brand identity" },
          { kind: "textarea", key: "text", label: "Short description (keep it to 1-2 sentences)", max: 140, hint: "Shown under the name when the photo opens; short text reads best." },
        ],
      },
      { kind: "text", key: "group", label: "Show the projects of this group (from Projects in the admin panel)", max: 30, hint: "Write brand to show the Brand Design projects you manage under Projects. Leave empty to use only the photos listed above." },
    ],
    defaults: { items: [{ image: "", title: "Project", category: "", text: "" }], group: "" },
  }),
  projects: defineSection({
    label: "Projects (our work)",
    description: "A grid of the projects you add under Projects in the admin panel (picture, name, short text). Every card opens the project page.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      { kind: "text", key: "group", label: "Only this group (empty = all projects)", max: 30, hint: "brand = the Brand Design projects. Empty shows every published project." },
    ],
    defaults: { chip: "Our work", heading: "Projects We\nAre Proud Of", intro: "", group: "" },
  }),
  process: defineSection({
    label: "Process steps",
    description: "Numbered steps (01, 02 …), each with a short text and small tags",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Steps",
        itemLabel: "Step",
        max: 10,
        fields: [
          { kind: "text", key: "title", label: "Title", max: 60 },
          { kind: "textarea", key: "text", label: "Text", max: 300 },
          { kind: "textarea", key: "points", label: "Small tags (one per line, optional)", max: 240 },
        ],
      },
    ],
    defaults: { chip: "Process", heading: "How we\nwork", intro: "", items: [{ title: "Step", text: "What happens in this step.", points: "Tag one\nTag two" }] },
  }),
  vrProcess: defineSection({
    label: "Process on the metaverse floor (Rutvi walks from station to station)",
    description: "The steps of the work as stations on a winding path on the floor of the metaverse studio. While the page scrolls, Rutvi walks from one station to the next and the card under the map tells what happens in that step. On a phone it is a plain list with a line down the side. Made for the Metaverse page.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Steps (the stations, from left to right)",
        itemLabel: "Step",
        max: 8,
        fields: [
          { kind: "text", key: "title", label: "Title", max: 60 },
          { kind: "textarea", key: "text", label: "Text", max: 300 },
          { kind: "textarea", key: "points", label: "What happens (one per line)", max: 240 },
        ],
      },
    ],
    defaults: { chip: "Process", heading: "How we\nwork", intro: "", items: [{ title: "Step", text: "What happens in this step.", points: "Point one\nPoint two" }] },
  }),
  tags: defineSection({
    label: "Tools / tags",
    description: "Heading and a cloud of small rounded tags (tools, technologies)",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      { kind: "textarea", key: "items", label: "Tags (one per line)", max: 800 },
    ],
    defaults: { chip: "Tools", heading: "Tools we\nuse", intro: "", items: "Tool one\nTool two" },
  }),
  backdrop7: defineSection({
    label: "Background: giant 7W monogram",
    description: "Page background: a very thick glowing 7 that turns into a W through a round junction node. Put it first.",
    fields: [],
    defaults: {},
  }),
  pageHero: defineSection({
    label: "Page hero",
    description: "First screen of an inner page: label, big heading, text and two buttons",
    fields: [
      chip(),
      headingField("Big heading"),
      { kind: "textarea", key: "text", label: "Text", max: 360 },
      { kind: "text", key: "primaryLabel", label: "First button text", max: 30 },
      { kind: "url", key: "primaryHref", label: "First button link" },
      { kind: "text", key: "secondaryLabel", label: "Second button text", max: 30 },
      { kind: "url", key: "secondaryHref", label: "Second button link" },
    ],
    defaults: { chip: "About", heading: "Big heading", text: "Text.", primaryLabel: "Learn more", primaryHref: "#about", secondaryLabel: "Our services", secondaryHref: "#services" },
  }),
  guide: defineSection({
    label: "Interactive guide (the cartoon at work)",
    description: "Text on one side and, on the other, a scene where the cartoon guide works with the technology of the page: its eyes follow the mouse, it talks and the visitor can play with the scene",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "text", label: "Text", max: 360 },
      { kind: "text", key: "scene", label: "Scene", max: 20, hint: "office (full screen), web, mobile, metaverse, uiux, crm, animation, modeling, graphics, seo, ai, brand or hello" },
      { kind: "textarea", key: "tips", label: "Things the guide says (one per line, it says them one after the other)", max: 900 },
      { kind: "text", key: "buttonLabel", label: "Button text (optional)", max: 30 },
      { kind: "url", key: "buttonHref", label: "Button link" },
    ],
    defaults: { chip: "Meet the guide", heading: "Say hello\nto our guide", text: "", scene: "hello", tips: "Hi! I am the guide of We3vision.", buttonLabel: "", buttonHref: "" },
  }),
  wordHero: defineSection({
    label: "Hero: giant swiping word",
    description: "First screen: one giant heavy word whose letters swipe through the same word in other languages, a tagline, text, two buttons, a live clock and your social links",
    fields: [
      {
        kind: "textarea",
        key: "words",
        label: "The word in different languages (one per line: Language label | Word)",
        max: 500,
        hint: "The first line is the main word (e.g. English · UK | Brand). Every letter swipes to the next line's word, then stands still for 1 second.",
      },
      { kind: "text", key: "heading", label: "Tagline (also the page heading for Google)", max: 160 },
      { kind: "textarea", key: "text", label: "Short text under the tagline", max: 300 },
      { kind: "text", key: "primaryLabel", label: "First button text", max: 30 },
      { kind: "url", key: "primaryHref", label: "First button link" },
      { kind: "text", key: "secondaryLabel", label: "Second button text", max: 30 },
      { kind: "url", key: "secondaryHref", label: "Second button link" },
      { kind: "text", key: "timezone", label: "Clock time zone", max: 40, hint: "e.g. Asia/Kolkata" },
      { kind: "text", key: "clockLabel", label: "Clock label", max: 8, hint: "e.g. IN" },
    ],
    defaults: {
      words: "English · UK | Brand",
      heading: "Tagline",
      text: "",
      primaryLabel: "Learn more",
      primaryHref: "#contact",
      secondaryLabel: "Our services",
      secondaryHref: "#services",
      timezone: "Asia/Kolkata",
      clockLabel: "IN",
    },
  }),
  timeline: defineSection({
    label: "Timeline",
    description: "Year-by-year story with a glowing line down the middle",
    fields: [
      chip(),
      headingField(),
      {
        kind: "list",
        key: "items",
        label: "Milestones",
        itemLabel: "Milestone",
        max: 16,
        fields: [
          { kind: "text", key: "year", label: "Year", max: 12 },
          { kind: "textarea", key: "text", label: "What happened", max: 240 },
        ],
      },
      { kind: "textarea", key: "names", label: "The three walkers, one per line: left, centre (walks to the end), right", max: 60, hint: "Example: Smit, Harsh, Vatsal. Three little characters in blazers walk down the line while you scroll." },
      { kind: "text", key: "leaveYear", label: "Year after which the left and the right one stop and sit on benches in a garden", max: 12, hint: "One of the years above, e.g. 2021" },
      { kind: "text", key: "partnerName", label: "Name of the one who joins the centre walker later", max: 24, hint: "e.g. Parth" },
      { kind: "text", key: "partnerYear", label: "Year in which he joins", max: 12, hint: "One of the years above, e.g. 2023" },
      { kind: "text", key: "finalYear", label: "Last screen: the big year", max: 8, hint: "e.g. 2027" },
      { kind: "text", key: "goalTitle", label: "Last screen: heading of the goal", max: 80 },
      { kind: "textarea", key: "goalText", label: "Last screen: the goal of the company", max: 300 },
      { kind: "textarea", key: "teams", label: "Last screen: the teams of the company, one per line (7 fit the office)", max: 400, hint: "Each name is written in small letters next to its tables." },
    ],
    defaults: { chip: "Journey", heading: "Heading\nsecond line", items: [{ year: "2019", text: "What happened." }], names: "Smit\nHarsh\nVatsal", leaveYear: "2021", partnerName: "Parth", partnerYear: "2023", finalYear: "2027", goalTitle: "Our goal", goalText: "What we want to achieve next.", teams: "Team one\nTeam two" },
  }),
  sketchCanvas: defineSection({
    label: "Sketch canvas (draw an idea, our artist makes it better)",
    description: "A drawing canvas with an ink brush: the visitor sketches a rough idea (or tries a sample), and a button opens the contact form with a message",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "text", label: "Text under the heading", max: 360 },
      { kind: "text", key: "hint", label: "Hint inside the empty canvas", max: 80 },
      { kind: "text", key: "sendLabel", label: "Button: send to the artist", max: 40 },
      { kind: "text", key: "saveLabel", label: "Button: save the sketch", max: 40 },
      { kind: "textarea", key: "sendMessage", label: "Message put in the contact form when the visitor sends the sketch", max: 400 },
      { kind: "textarea", key: "steps", label: "Three steps under the canvas (one per line: Title | short text)", max: 600 },
    ],
    defaults: {
      chip: "Your idea, our artist",
      heading: "Draw a rough idea\nwe make it shine",
      text: "A small sketch is enough. Draw it here and send it to our artist, who turns it into a clean brand mark.",
      hint: "Press and draw your rough idea here",
      sendLabel: "Send to our artist",
      saveLabel: "Save my sketch",
      sendMessage: "Hi We3vision team, I drew a rough idea on your brand canvas and would like your artist to make it beautiful. I have saved the sketch as an image and will send it to you. About my business: ",
      steps: "Draw it | A few lines are enough: a shape, a letter, a feeling.\nWe study it | We look at your business, your audience and the idea behind your lines.\nOur artist returns it | A clean, balanced brand mark that lifts the value of your brand.",
    },
  }),
  vrEntry: defineSection({
    label: "Metaverse entrance (3D office walk)",
    description: "A full 3D office: scrolling walks the visitor to a table where a VR headset waits; it is put on and the screen goes black. Put it first on the page.",
    fields: [
      { kind: "text", key: "heading", label: "Page heading (read by Google and screen readers, shown while the office loads)", max: 120 },
      { kind: "textarea", key: "text", label: "Short text under the heading (same use)", max: 360 },
      { kind: "text", key: "hint", label: "Hint at the start", max: 40, hint: "e.g. Scroll to walk in" },
      { kind: "textarea", key: "captions", label: "Four short lines shown while walking (one per line)", max: 400, hint: "Shown one after the other: at the door, in the office, at the table, with the headset." },
    ],
    defaults: {
      heading: "Metaverse Solutions For\nImmersive Experiences",
      text: "We3vision builds metaverse concepts, virtual worlds and interactive digital experiences around your business goals.",
      hint: "Scroll to walk in",
      captions: "Welcome to the We3vision studio.\nThis is where ideas become worlds.\nOne more step.\nPut it on.",
    },
  }),
  vrSpace: defineSection({
    label: "Metaverse space (glass windows inside the headset)",
    description: "The view inside the headset: a space behind a soft blur and three glass windows that come to the middle one after the other while scrolling. It follows the 3D office.",
    fields: [
      {
        kind: "list",
        key: "windows",
        label: "Windows (the first one is on the left and comes first)",
        itemLabel: "Window",
        max: 3,
        fields: [
          { kind: "text", key: "eyebrow", label: "Small label", max: 40 },
          { kind: "text", key: "title", label: "Title", max: 80 },
          { kind: "textarea", key: "text", label: "Text", max: 220 },
          { kind: "image", key: "image", label: "Picture (leave empty for the drawn scene)", hint: "A wide picture works best (16:7). Leave empty to use the artwork that is built in." },
          { kind: "textarea", key: "cards", label: "Three small cards, one per line: Title | short text", max: 400 },
        ],
      },
    ],
    defaults: {
      windows: [{ eyebrow: "Education & training", title: "Learn by doing, in a virtual classroom", text: "Virtual classrooms and training spaces let students and teams practise, explore and work together from anywhere.", image: "", cards: "Virtual classrooms | Live lessons in a shared 3D space\nSkill & safety training | Practise safely before the real thing\nVirtual campuses | A place to meet, learn and belong" }],
    },
  }),
  aboutWorld: defineSection({
    label: "About: 3D story with the panda",
    description: "The top of the About page as one 3D story: a floating island with five stations (one chapter each) and Pando the panda who shows the way and says hello at the end. Put it first on the page.",
    fields: [
      {
        kind: "group",
        key: "hero",
        label: "First screen",
        fields: [
          { kind: "text", key: "chip", label: "Small label", max: 40 },
          { kind: "textarea", key: "heading", label: "Big heading (the page heading for Google)", max: 120, hint: LINES_HINT },
          { kind: "textarea", key: "text", label: "Text", max: 360 },
          { kind: "text", key: "primaryLabel", label: "First button text (goes to the story)", max: 30 },
          { kind: "text", key: "secondaryLabel", label: "Second button text", max: 30 },
          { kind: "url", key: "secondaryHref", label: "Second button link" },
        ],
      },
      {
        kind: "list",
        key: "chapters",
        label: "Chapters (one per station of the island, in this order: office, the year, the place, the services, the mission)",
        itemLabel: "Chapter",
        max: 5,
        fields: [
          { kind: "text", key: "title", label: "Title", max: 60 },
          { kind: "textarea", key: "text", label: "Text", max: 240 },
        ],
      },
      {
        kind: "group",
        key: "meet",
        label: "The panda at the end",
        fields: [
          { kind: "text", key: "chip", label: "Small label", max: 40 },
          { kind: "textarea", key: "heading", label: "Heading", max: 80, hint: LINES_HINT },
          { kind: "textarea", key: "text", label: "Text", max: 240 },
          { kind: "textarea", key: "tips", label: "Things the panda says (one per line)", max: 700 },
        ],
      },
    ],
    defaults: {
      hero: {"chip":"About Us","heading":"Empowering Digital Transformation\nThrough Innovation","text":"At We3vision Private Limited we are dedicated to transforming how people live digitally. Since 2019 we have been at the forefront of digital innovation, delivering cutting-edge solutions that empower businesses and individuals alike.","primaryLabel":"Discover our story","secondaryLabel":"Our services","secondaryHref":"#services"},
      chapters: [{"title":"A leading IT service company","text":"We3vision Private Limited blends technology, design and strategy to deliver high-performance solutions for businesses and individuals."},{"title":"Founded in 2019","text":"Born in Surat with a vision to deliver innovative, customer-focused IT solutions, and growing every year since."},{"title":"Based in Surat, India","text":"Our headquarters and development office are in Surat, Gujarat. We build custom digital solutions for companies across India and the globe."},{"title":"Everything digital, one team","text":"Web and app development, AR, VR, XR, CGI and 3D animation, CRM, ERP and digital branding: delivered by one skilled team."},{"title":"Ideas into impactful realities","text":"With a skilled team, strong values and a vision for innovation, we turn your ideas into reality, from a dynamic website to immersive virtual experiences."}],
      meet: {"chip":"Meet our mascot","heading":"Say hello to\nPando","text":"Pando is the little panda of We3vision. It shows you around the studio, so say hello: click it and move your mouse.","tips":"Hi! I am Pando, the panda of We3vision.\nWe are a Surat-based studio, working since 2019.\nWeb, AI, AR/VR, metaverse, apps, CRM and 3D: we do it all.\nBamboo helps me think. Ideas help you grow.\nScroll down to see our journey and our leaders."},
    },
  }),
  vrFloor: defineSection({
    label: "Metaverse office (top view: Rutvi sits down, four teams AR / VR / XR / MR)",
    description: "The office of the metaverse team seen from above, drawn like the office of 2027 on the About page: the heading on the floor, Rutvi walks in and sits at her desk, and the four teams (AR, VR, XR, MR) work in the four corners. Pointing at a team shows what it does and which industries it can help.",
    fields: [
      { kind: "textarea", key: "heading", label: "Heading on the floor (one short line each)", max: 90, hint: LINES_HINT },
      { kind: "text", key: "hint", label: "Hint at the door", max: 40 },
      { kind: "text", key: "name", label: "Name of the girl who walks in", max: 20 },
      { kind: "text", key: "tipTitle", label: "Title of the card under her desk", max: 50 },
      { kind: "textarea", key: "tipText", label: "Text of the card under her desk", max: 200 },
      { kind: "text", key: "industriesTitle", label: "Line above the industries in the pop-up", max: 120 },
      { kind: "text", key: "ctaLabel", label: "Button in the pop-up (goes to the contact section)", max: 30 },
      { kind: "text", key: "govTitle", label: "Heading outside the office, above the two government projects", max: 60 },
      {
        kind: "list",
        key: "projects",
        label: "The two government projects outside the office (first one on the left, second one on the right)",
        itemLabel: "Project",
        max: 2,
        fields: [
          { kind: "text", key: "org", label: "Name of the department (big)", max: 12 },
          { kind: "text", key: "orgFull", label: "Full name of the department", max: 80 },
          { kind: "text", key: "mark", label: "Letters inside the round badge (used when there is no logo)", max: 3 },
          { kind: "image", key: "logo", label: "Logo (optional)", hint: "Image path or link, e.g. /images/logos/nrida.png. Leave empty to show the letters." },
          { kind: "text", key: "title", label: "Project name", max: 80 },
          { kind: "text", key: "status", label: "Status", max: 20, hint: "e.g. Delivered or Ongoing" },
          { kind: "text", key: "period", label: "Period", max: 40 },
          { kind: "text", key: "by", label: "Who developed it", max: 120 },
          { kind: "textarea", key: "text", label: "About the project", max: 400 },
          { kind: "textarea", key: "steps", label: "Stages shown in the project (one per line)", max: 300, hint: "They light up one after the other." },
          { kind: "textarea", key: "tags", label: "Tools (one per line)", max: 200 },
          { kind: "textarea", key: "team", label: "Team (one per line: Name | Role)", max: 400 },
        ],
      },
      {
        kind: "list",
        key: "cabins",
        label: "The four teams (the corners of the office, in this order: top left, top right, bottom left, bottom right)",
        itemLabel: "Team",
        max: 4,
        fields: [
          { kind: "text", key: "code", label: "Short code", max: 4 },
          { kind: "text", key: "name", label: "Name", max: 40 },
          { kind: "textarea", key: "text", label: "Short text (shown in the pop-up)", max: 200 },
          { kind: "textarea", key: "industries", label: "Industries this service is possible for (one per line)", max: 400, hint: LINES_HINT },
        ],
      },
    ],
    defaults: {
      heading: "Tech services\nwe offer in\nthe metaverse",
      hint: "Scroll to follow Rutvi",
      name: "Rutvi",
      tipTitle: "Which team is for you?",
      tipText: "Point at one of the four teams to see what it builds and which industries it can help. On a phone, tap a team.",
      industriesTitle: "If you work in one of these industries, this tech service is possible for you",
      ctaLabel: "Talk to us",
      govTitle: GOV_TITLE,
      projects: GOV_PROJECTS,
      cabins: [{"code":"AR","name":"Augmented Reality","text":"Digital layers on top of the real world: product previews, interactive guides and try-ons on a phone or tablet.","industries":"Retail & e-commerce\nReal estate\nFurniture & interiors\nEducation\nHealthcare\nTourism & hospitality"},{"code":"VR","name":"Virtual Reality","text":"Fully immersive virtual worlds, showrooms and training that people step into with a headset.","industries":"Real estate\nEducation & training\nGaming & entertainment\nManufacturing\nHealthcare\nEvents & exhibitions"},{"code":"XR","name":"Extended Reality","text":"The umbrella for AR, VR and MR: immersive experiences planned across devices and platforms.","industries":"Retail & fashion\nAutomotive\nEducation\nHealthcare\nCorporate & HR\nMedia & events"},{"code":"MR","name":"Mixed Reality","text":"Virtual objects that sit in the real space around you and respond to it: demos, visualisation and teamwork.","industries":"Architecture & construction\nManufacturing\nHealthcare\nEngineering & design\nAutomotive\nCorporate teams"}],
    },
  }),
  vrDevices: defineSection({
    label: "Device board (list of devices, a big stage and a filter)",
    description: "A board of devices and platforms (headsets, phone AR, the browser, game engines): a list on the left and a big stage on the right that shows the chosen device, what the company builds for it and a button to the contact form. It changes device by itself; the filter shows which devices fit AR, VR, XR or MR. Below it a strip with the technology used.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "items",
        label: "Devices and platforms",
        itemLabel: "Device",
        max: 9,
        fields: [
          { kind: "text", key: "name", label: "Name", max: 50 },
          { kind: "text", key: "kind", label: "Small label (the kind of device)", max: 30 },
          { kind: "text", key: "realities", label: "Which realities it fits", max: 20, hint: "Any of AR VR XR MR, separated by spaces, e.g. AR VR" },
          { kind: "textarea", key: "text", label: "What we build for it", max: 300 },
          { kind: "textarea", key: "tags", label: "Tools (one per line)", max: 160 },
        ],
      },
      { kind: "text", key: "ctaLabel", label: "Button under a device (goes to the contact form)", max: 40 },
      { kind: "text", key: "toolsLabel", label: "Heading of the technology strip", max: 50 },
      { kind: "textarea", key: "tools", label: "Technology strip (one per line)", max: 600 },
    ],
    defaults: DEVICES,
  }),
  vrQuiz: defineSection({
    label: "Quiz: which reality fits your idea (AR, VR, XR or MR)",
    description: "Three questions with big answer buttons, then a recommendation (AR, VR, XR or MR) and a button that takes the visitor to the contact form with the answers already written in the message.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      { kind: "text", key: "startLabel", label: "Button that starts the quiz", max: 24 },
      { kind: "text", key: "restartLabel", label: "Button to start again", max: 24 },
      { kind: "text", key: "ctaLabel", label: "Button under the answer (goes to the contact form)", max: 40 },
      {
        kind: "list",
        key: "questions",
        label: "Questions",
        itemLabel: "Question",
        max: 5,
        fields: [
          { kind: "text", key: "question", label: "Question", max: 100 },
          {
            kind: "textarea",
            key: "options",
            label: "Answers (one per line: the answer | the realities it points to)",
            max: 800,
            hint: "e.g. Train people | VR. A reality written twice counts twice. The reality with most points is the answer; when several tie, the answer is XR.",
          },
        ],
      },
      {
        kind: "list",
        key: "results",
        label: "The four answers",
        itemLabel: "Answer",
        max: 4,
        fields: [
          { kind: "text", key: "code", label: "Code (AR, VR, XR or MR)", max: 4 },
          { kind: "text", key: "title", label: "Title", max: 60 },
          { kind: "textarea", key: "text", label: "Why it fits", max: 400 },
          { kind: "text", key: "project", label: "A good first step", max: 200 },
        ],
      },
    ],
    defaults: QUIZ,
  }),
  teamOffice: defineSection({
    label: "Team office (the people at their desks, camera goes room to room)",
    description: "The office seen from above with a room for every department and the people at the table (20 to 30 fit well). The page scrolls the camera from room to room; pointing at a person shows a card with the photo, name, role, a few words and a link. On a phone: the same people as cards.",
    fields: [
      chip(),
      headingField(),
      { kind: "textarea", key: "intro", label: "Intro text", max: 300 },
      {
        kind: "list",
        key: "members",
        label: "People (the rooms are made from the Department names, in the order of the first person of each)",
        itemLabel: "Person",
        max: 40,
        fields: [
          { kind: "text", key: "name", label: "Name", max: 60 },
          { kind: "text", key: "role", label: "Role", max: 70 },
          { kind: "text", key: "dept", label: "Department", max: 30, hint: "People with the same department sit in the same room" },
          { kind: "textarea", key: "bio", label: "A few words about the person", max: 260 },
          { kind: "image", key: "photo", label: "Photo (optional)", hint: "Image path or link. Without a photo the initials are shown." },
          { kind: "url", key: "linkedin", label: "LinkedIn link (optional)" },
          { kind: "text", key: "girl", label: "Draw as a girl (type yes)", max: 3 },
        ],
      },
    ],
    defaults: { chip: "The office", heading: "Meet The Team", intro: "", members: TEAM_MEMBERS },
  }),
  aboutHero: defineSection({
    label: "About: first screen (words on a grid floor)",
    description: "The first screen of the About page as words: label, big heading, text and two buttons, in front of a grid floor in perspective. No 3D scene.",
    fields: [
      chip(),
      headingField("Big heading (the page heading for Google)"),
      { kind: "textarea", key: "text", label: "Text", max: 360 },
      { kind: "text", key: "primaryLabel", label: "First button text (goes to the story)", max: 30 },
      { kind: "url", key: "primaryHref", label: "First button link" },
      { kind: "text", key: "secondaryLabel", label: "Second button text", max: 30 },
      { kind: "url", key: "secondaryHref", label: "Second button link" },
    ],
    defaults: { chip: "About Us", heading: "About\nWe3vision", text: "", primaryLabel: "Discover our story", primaryHref: "#story", secondaryLabel: "Our services", secondaryHref: "#services" },
  }),
  aboutChapters: defineSection({
    label: "About: our story in chapters (with the panda)",
    description: "The story of the company as chapters on a line that is drawn while the page scrolls, and a card where the panda says a few things.",
    fields: [
      chip(),
      headingField(),
      {
        kind: "list",
        key: "chapters",
        label: "Chapters",
        itemLabel: "Chapter",
        max: 8,
        fields: [
          { kind: "text", key: "title", label: "Title", max: 60 },
          { kind: "textarea", key: "text", label: "Text", max: 240 },
        ],
      },
      {
        kind: "group",
        key: "meet",
        label: "The panda at the end",
        fields: [
          { kind: "text", key: "chip", label: "Small label", max: 40 },
          { kind: "textarea", key: "heading", label: "Heading", max: 80, hint: LINES_HINT },
          { kind: "textarea", key: "text", label: "Text", max: 240 },
          { kind: "textarea", key: "tips", label: "Things the panda says (one per line)", max: 700 },
        ],
      },
    ],
    defaults: { chip: "Our story", heading: "Our Story", chapters: [{ title: "Chapter", text: "Text." }], meet: { chip: "Meet our mascot", heading: "Say hello to\nPando", text: "", tips: "Hi!" } },
  }),
  vrEmerge: defineSection({
    label: "Fade from black into the page",
    description: "A soft band that dissolves the black of the 3D scenes into the normal page, slowly and with a blur that clears. Put it between the scenes and the rest of the page.",
    fields: [],
    defaults: {},
  }),
  team: defineSection({
    label: "Team / leaders",
    description: "People cards with a round initials avatar, name and role",
    fields: [
      chip(),
      headingField(),
      {
        kind: "list",
        key: "members",
        label: "People",
        itemLabel: "Person",
        max: 9,
        fields: [
          { kind: "text", key: "name", label: "Name", max: 60 },
          { kind: "text", key: "role", label: "Role", max: 80 },
        ],
      },
    ],
    defaults: { chip: "Team", heading: "Heading\nsecond line", members: [{ name: "Full Name", role: "Role" }] },
  }),
} as const;

export type SectionType = keyof typeof SECTIONS;
export type SectionData<T extends SectionType> = (typeof SECTIONS)[T]["defaults"];
export const SECTION_TYPES = Object.keys(SECTIONS) as SectionType[];
export const isSectionType = (v: unknown): v is SectionType => typeof v === "string" && Object.hasOwn(SECTIONS, v);
