// LOCKED: confirmed by the user. Do not edit this file without asking the user first.

// The detail points that go under the "What we build" strip of every service page (service-strip.tsx): for each sub-service when it is the
// right choice (fit), which problems it solves and what the visitor gets out of it. They scroll along with the panels of the strip. Plain
// statements about what the work is for: no prices, no client names and no numbers or promises beyond what the old site says.
// The key is the card title on one line. Lists are lines separated by a line break (the same format as the other lists of the site).

export type ServiceDetail = { fit: string; problems: string; outcomes: string };

const d = (fit: string, problems: string[], outcomes: string[]): ServiceDetail => ({ fit, problems: problems.join("\n"), outcomes: outcomes.join("\n") });

export const SERVICE_DETAILS: Record<string, ServiceDetail> = {
  // ---- web development
  "WordPress & WooCommerce": d(
    "You want a website you can update yourself, or a store you can run without calling a developer.",
    ["Every small text change needs a developer", "A generic template that looks like everyone else's", "No easy way to add products, pages or blog posts"],
    ["A site you edit yourself from a simple dashboard", "A design built for your brand, not a template", "Training, so your team is confident from day one"],
  ),
  "Shopify Stores": d(
    "You want to start selling online quickly, with payments, orders and shipping handled for you.",
    ["Shoppers leave before they check out", "Products, orders and payments spread over many places", "A store that is slow or awkward on a phone"],
    ["A store built to turn visitors into buyers", "Orders, stock and payments in one place", "A smooth shopping experience on every device"],
  ),
  "Headless CMS": d(
    "Speed and flexibility matter more than a ready-made theme, or one source of content must feed several places.",
    ["A slow site that hurts search ranking and sales", "Content locked into one theme or one channel", "A front end that is hard to change or grow"],
    ["Very fast pages with React, Vue or Angular", "Editors keep an easy CMS, developers keep their freedom", "One content source for the web, an app and more"],
  ),
  "E-commerce Websites": d(
    "Your store needs custom features, many products or its own checkout that a template cannot give you.",
    ["Platform limits that block the features you need", "Stock, payments and orders that do not connect", "A store that struggles as sales grow"],
    ["A store shaped around your products and customers", "Payments and inventory working together", "A secure base that scales with your business"],
  ),
  "Custom Web Portals": d(
    "You need more than pages: bookings, listings, courses, accounts or dashboards.",
    ["Bookings and requests handled by phone and spreadsheets", "No single place where users log in and manage things", "Off-the-shelf tools that do not fit your process"],
    ["A portal that takes over the manual work", "Secure logins and roles for each type of user", "A system that is yours and can grow with you"],
  ),
  "Domain, Hosting & SSL": d(
    "You are launching, moving a site, or you simply do not want to deal with the technical set-up.",
    ["Not sure which domain or hosting to buy", "Browser warnings about an insecure site", "A site that is slow or goes offline"],
    ["Domain, hosting and SSL set up for you", "A secure site with the padlock visitors look for", "Deployed on secure servers, ready to go live"],
  ),

  // ---- mobile apps
  "Android Apps": d(
    "Most of your customers use Android, or you want to reach the widest range of phones.",
    ["Your product is not on your customers' phones", "An app that is slow or crashes on some devices", "Unclear how to build for so many different devices"],
    ["A fast app tuned for the devices your users have", "Native Kotlin or cross-platform, picked to fit your goal", "A clean interface that is easy to use"],
  ),
  "iOS Apps": d(
    "Your audience is on iPhone and iPad, or you want a polished product that is ready for the App Store.",
    ["Worry that the App Store will reject the app", "An interface that does not feel at home on iPhone", "Slow or unstable performance"],
    ["A native Swift app with a clean, brand-aligned look", "Built to meet the App Store guidelines", "Smooth performance on iPhone and iPad"],
  ),
  "Cross-platform & Hybrid Apps": d(
    "You want Android and iOS together without paying for two separate builds.",
    ["Two apps mean double the cost and time", "Features that differ between Android and iOS", "Two codebases that are hard to keep up to date"],
    ["One codebase for both platforms (Flutter or React Native)", "The same look and features everywhere", "Faster delivery and simpler updates"],
  ),
  "MVP Development": d(
    "You have an idea and want to test it with real users before a big investment.",
    ["Not sure the idea will work", "A long, costly build before any feedback", "Too many features and too little focus"],
    ["A focused first version with the core features", "A launch you can learn from quickly", "A clear base to grow from, shaped by real feedback"],
  ),
  "Full-scale Products": d(
    "Your app needs accounts, data, real-time features and a path to grow.",
    ["A simple app that cannot handle growth", "Data that is not stored or synced reliably", "No plan for updates and new features"],
    ["APIs, real-time sync and secure authentication", "Storage that grows with your users", "Continuous updates as your product evolves"],
  ),
  "Store Launch & Maintenance": d(
    "The app is ready, or nearly, and you want a smooth launch and care afterwards.",
    ["Unsure how to publish on Google Play and the App Store", "A listing that does not attract downloads", "Bugs and system updates after launch"],
    ["Submission to both stores handled for you", "Listing optimization to help people find the app", "Monitoring, fixes and new features after launch"],
  ),

  // ---- metaverse
  "Metaverse Development": d(
    "You want to enter the metaverse but need a plan that fits your business.",
    ["Unclear what the metaverse can do for your brand", "Technology that does not match your audience", "No roadmap from idea to launch"],
    ["An experience planned around your goals and audience", "A clear vision for the whole project", "A team that takes it from concept to launch"],
  ),
  "Metaverse Applications": d(
    "You need a platform with specific features and links to your other systems.",
    ["The features your idea needs do not exist off the shelf", "Experiences that cannot connect to your other tools", "A platform that feels disconnected"],
    ["Applications built with the features you need", "Integrations with your existing systems", "An experience that feels like one product"],
  ),
  "Virtual World Development": d(
    "You want a world of your own, with its own look, structure and flow.",
    ["Generic worlds that look like everyone else's", "No clear way for visitors to move through the experience", "Assets that do not fit together"],
    ["A custom world with its own structure and style", "Original 3D assets and a clear visual direction", "A flow that guides visitors naturally"],
  ),
  "Virtual Events & Experiences": d(
    "You want to launch, present or gather people without a physical venue.",
    ["An audience too far away to attend in person", "Online events that feel flat and forgettable", "The cost and effort of physical events"],
    ["Virtual events and launches people can join from anywhere", "Interactive experiences that keep attention", "A digital gathering for your business or community"],
  ),
  "Interactive 3D Experiences": d(
    "You want visitors to explore, play or interact rather than only look.",
    ["Static pages that do not hold attention", "A product or place that is hard to show in a flat image", "Games and experiences that need real 3D work"],
    ["Immersive 3D experiences and games", "Products and places people can explore", "An experience that is remembered"],
  ),
  "NFT & Digital Asset Platforms": d(
    "You want to create, sell or trade digital assets with wallet support.",
    ["No platform to mint, list or trade digital assets", "Wallets and payments that are hard to connect", "Storage for the assets that is not reliable"],
    ["A marketplace with wallet integration", "Built with Ethereum, Polygon and IPFS", "A platform ready for your collection or community"],
  ),

  // ---- UI/UX
  "UX Research & Strategy": d(
    "You are starting something new, or you do not know why users leave.",
    ["Designing on guesses instead of facts", "Not knowing what users really need", "Competitors that seem to be ahead"],
    ["Insight from user interviews and competitor analysis", "Behaviour mapped to a clear design direction", "Decisions you can explain and trust"],
  ),
  "Information Architecture": d(
    "Your site or app has a lot of content and people cannot find things.",
    ["Visitors lost in the menu", "Content grouped the way you think, not the way users do", "A flow with dead ends"],
    ["A clear navigation hierarchy", "Content grouped the way users think", "A flow that gets people to what they need"],
  ),
  "Wireframes & Prototypes": d(
    "You want to see and test an idea before it is built.",
    ["Surprises after development starts", "Team members who imagine different things", "Expensive changes late in the project"],
    ["Low and high fidelity wireframes", "Clickable prototypes to try the flow", "Problems found early, when they are cheap to fix"],
  ),
  "UI Design & Visual Branding": d(
    "Your product works but looks dated or inconsistent, or does not feel like your brand.",
    ["An interface that looks generic", "Colours and type that do not match the brand", "A layout that feels cluttered"],
    ["A modern interface in your brand's tone", "Colour, typography and icons that work together", "Balanced layouts that are a pleasure to use"],
  ),
  "Interaction & Motion Design": d(
    "Your product feels static or abrupt and you want it to feel alive.",
    ["Screens that change with no feedback", "Loading that feels long and blank", "Buttons and menus that feel flat"],
    ["Subtle animations, from hover effects to loading states", "Transitions that explain what is happening", "Interactions that feel natural"],
  ),
  "Responsive & Adaptive Design": d(
    "Your users come from phones, tablets and desktops, or even AR and VR.",
    ["A layout that breaks on some screens", "A different experience on each device", "Tiny text and buttons on mobile"],
    ["Designs for web, mobile and tablet, even AR/VR", "One consistent experience everywhere", "Controls and text that work on every screen"],
  ),
  "Usability Testing & Optimization": d(
    "You have a design or a product and want proof that real people can use it.",
    ["Users dropping off and you do not know why", "Opinions instead of evidence", "Friction hidden in the flow"],
    ["Tests with real users", "Friction points found and explained", "Refinements based on the feedback"],
  ),
  "Design Systems & Style Guides": d(
    "Your team ships many screens and they must look and behave the same.",
    ["Every screen a little different", "Designers and developers rebuilding the same parts", "Slow, inconsistent updates"],
    ["Reusable UI kits and colour libraries", "Clear style guidelines for every touchpoint", "Faster design and development"],
  ),
  "UI/UX Audit & Redesign": d(
    "You already have a product that underperforms and want to know what to fix.",
    ["Low engagement and no clear reason", "Accessibility gaps", "A product that has outgrown its design"],
    ["A detailed audit of what works and what does not", "A redesign that improves performance and accessibility", "A product people engage with more"],
  ),

  // ---- CRM
  "Sales CRM": d(
    "Your team tracks leads in spreadsheets, chats or memory.",
    ["Leads that slip through the cracks", "No clear view of the pipeline", "Guesswork when forecasting deals"],
    ["Leads and pipelines tracked in one place", "Deal forecasts you can actually see", "A team that closes deals more efficiently"],
  ),
  "Marketing CRM": d(
    "You run campaigns and want to know what really works.",
    ["Campaigns sent to everyone in the same way", "No clear picture of who engages", "Manual follow-ups"],
    ["Automated campaigns", "Engagement tracked for every user", "Segmented audiences and better conversions"],
  ),
  "Customer Support CRM": d(
    "Customer requests arrive through many channels and some get lost.",
    ["Tickets spread over inboxes and chats", "Missed deadlines for replies", "No feedback loop"],
    ["Tickets centralised in one place", "SLAs managed and visible", "Chat integrations and feedback loops"],
  ),
  "ERP Software & Connectors": d(
    "Your tools do not talk to each other and teams keep copying data by hand.",
    ["The same data entered in several systems", "Reports that do not match", "Slow handovers between teams"],
    ["ERP and CMS connectors", "One source of data for all your systems", "Less manual work and fewer mistakes"],
  ),
  "Lead Tracking & Automation": d(
    "Enquiries come in by email, ads and WhatsApp and nobody follows up in time.",
    ["Late replies to new leads", "No record of where each lead came from", "The same manual work, again and again"],
    ["Pipelines with automation", "Email, analytics and the WhatsApp Business API connected", "Faster follow-up on every lead"],
  ),
  "Inventory & Support": d(
    "You need to track stock and customer requests and keep the team trained.",
    ["Stock numbers that are never right", "Customer requests that wait", "A team unsure how to use the system"],
    ["Stock and requests tracked in one system", "Team onboarding and training", "Ongoing support after launch"],
  ),

  // ---- animation
  "2D Animation": d(
    "You need to explain something simply or tell your brand story.",
    ["A complex idea that is hard to explain", "Campaigns that blend into the feed", "Dry educational content"],
    ["Engaging explainers and promotional videos", "Educational content people watch to the end", "Brand storytelling with personality"],
  ),
  "3D Animation": d(
    "You want to show a product or an idea that cannot be filmed, or not in this detail.",
    ["A product that is not built yet", "Flat images that do not show how it works", "Concepts that are hard to picture"],
    ["Products and concepts brought to life in 3D", "3D product visualization and animation", "Visuals that support your promotions"],
  ),
  "CGI & 3D Visualization": d(
    "You need realistic visuals for a launch, a pitch or your marketing.",
    ["No photos of something that does not exist yet", "Photo shoots that are costly and slow", "Ideas that are hard to communicate"],
    ["Realistic visual content of products and ideas", "Visuals that support your promotions", "A clear way to communicate the idea"],
  ),

  // ---- 3D modeling
  "3D Product Models": d(
    "You sell products and want to show them in detail, or let customers explore them.",
    ["Photos that hide the details", "Catalogs that are hard to update", "Customers unsure what they are buying"],
    ["Custom product models", "3D visualization for presentations and catalogs", "Interactive shopping experiences"],
  ),
  "3D Assets & Environments": d(
    "You are building a game, a walkthrough or an immersive experience and need the pieces.",
    ["No time to model every object", "Assets that do not match in style", "Environments that feel empty"],
    ["Characters, props and environments", "A consistent look across the project", "Ready for games, walkthroughs and immersive experiences"],
  ),
  "Texturing & Lighting": d(
    "Your models exist but do not look real or finished.",
    ["Flat, plastic-looking models", "Lighting that hides the detail", "A look that differs from what you intended"],
    ["PBR materials and realistic textures", "Lighting setups and look development", "Models that look as intended"],
  ),
  "Optimization for Platforms": d(
    "Your 3D has to run smoothly in AR, VR, the browser or the metaverse.",
    ["Models too heavy to load", "Lag and low frame rates", "Assets that do not work on your platform"],
    ["High and low-poly versions", "Polygon optimization", "Smooth use on interactive, AR, VR and metaverse platforms"],
  ),

  // ---- graphics
  "Website & App UI/UX Design": d(
    "You are building or rebuilding a website or an app and the interface comes first.",
    ["An interface that confuses users", "A different look on web and mobile", "Design and development that are not lined up"],
    ["Website, responsive and mobile app interfaces", "A design for the whole product ecosystem", "Screens that are ready for development"],
  ),
  "E-commerce Design": d(
    "Your store gets visits but not enough orders.",
    ["Shoppers leave at the checkout", "Product pages that do not persuade", "A storefront that looks like a template"],
    ["Conversion-optimized storefronts", "Product cards that sell", "Intuitive checkout flows"],
  ),
  "Logo & Brand Identity": d(
    "You are starting a brand, or your brand looks inconsistent.",
    ["A logo that is forgettable", "No rules for colours, type and use", "Materials that do not look like one brand"],
    ["Logo design", "Brand guidelines", "A distinctive, memorable brand presence"],
  ),
  "Marketing Graphics": d(
    "You need creatives for ads, social media and campaigns that look consistent.",
    ["Posts and ads that look different every time", "No time to design every creative", "Landing pages that do not match the campaign"],
    ["Advertising creatives and social content", "Campaign landing pages", "Brand collateral in one consistent style"],
  ),
  "Pitch Decks & Presentations": d(
    "You are presenting to investors, clients or your team and the story has to land.",
    ["Slides crowded with text", "A story that is hard to follow", "A deck that does not look credible"],
    ["Investor pitch decks", "Presentation design that tells your story clearly", "A professional look"],
  ),
  "Design Systems": d(
    "Your product spans several platforms and must stay consistent as it grows.",
    ["Inconsistency between platforms", "Redesigning the same parts again and again", "Growth that makes the design messy"],
    ["A consistent product across platforms", "Simpler future growth", "Faster design and development"],
  ),

  // ---- SEO
  "Website Audit & Analysis": d(
    "Your traffic is flat or you do not know what is holding the site back.",
    ["No idea why the site is not ranking", "Technical problems nobody has checked", "Competitors ahead and no clue how"],
    ["A technical audit and gap analysis", "Opportunities mapped out", "Competitor benchmarking"],
  ),
  "Keyword Research": d(
    "You are not sure which searches your customers really use.",
    ["Targeting words nobody searches for", "Missing the high-value keywords", "Content that does not match what people want"],
    ["Competitors studied for the keywords that matter", "High-value keywords tied to your goals", "Content aimed at search intent"],
  ),
  "On-Page Optimization": d(
    "Your pages exist but are not clear to Google or to visitors.",
    ["Missing or duplicate titles and descriptions", "Headings and images that are not optimized", "Pages that do not link to each other well"],
    ["Meta tags, headings and images optimized", "Internal links that help search engines", "Better relevance and visibility"],
  ),
  "Technical SEO": d(
    "Your site is slow, hard to use on a phone, or hard for search engines to crawl.",
    ["Slow pages", "A site that is not mobile friendly", "Crawling and indexing problems"],
    ["Faster pages and mobile responsiveness", "Crawlability and Core Web Vitals", "Structured data for strong technical health"],
  ),
  "Content Strategy & Optimization": d(
    "You publish content but it does not bring visitors, or you have no plan.",
    ["Content that does not match what people search for", "Old pages that were never improved", "No editorial plan"],
    ["Existing content refined", "New pages aligned with search intent", "Briefs and an editorial calendar"],
  ),
  "Link Building & Local SEO": d(
    "You want more trust online and more customers from your own area.",
    ["Few links and mentions from other sites", "Not showing up in local searches", "Business details that are not consistent"],
    ["Quality backlinks through ethical outreach", "Citations and brand signals", "A Google Business Profile and location pages"],
  ),
};

/** The detail of a card, found by its title (the line breaks of the title do not matter). */
export const detailFor = (title: string): ServiceDetail | undefined => SERVICE_DETAILS[title.replace(/\s*\n\s*/g, " ").trim()];
