// What each technology / tool of the "Tools & Technologies" sections is good for (the pop-up that opens when you hover or tap a technology in
// tech-space.tsx): a short line about it, three examples of what can be built with it, the kinds of business it suits and why we use it.
// Plain statements about the work: no prices, no client names, no numbers or promises. The key is the name as it is written in the tool lists.

export type TechDetail = { cat: string; tagline: string; builds: string[]; industries: string[]; why: string };

const t = (cat: string, tagline: string, builds: string[], industries: string[], why: string): TechDetail => ({ cat, tagline, builds, industries, why });

export const TECH_DETAILS: Record<string, TechDetail> = {
  // ---- front end
  HTML5: t("Front-end", "The structure of every web page.", ["Landing pages and company websites", "Accessible forms and content pages", "Email-friendly and print-friendly layouts"], ["Startups", "Agencies", "Education"], "Clean, meaningful HTML makes pages faster, easier to find on Google and easier to use."),
  CSS3: t("Front-end", "Layout, colour and motion on the web.", ["Responsive layouts for every screen", "Smooth animations and transitions", "Themes and design systems"], ["Marketing sites", "E-commerce", "SaaS products"], "It lets one design look right on a phone, a tablet and a wide desktop screen."),
  JavaScript: t("Front-end", "The language that makes pages interactive.", ["Interactive dashboards", "Live search, filters and forms", "Web apps that feel like native apps"], ["E-commerce", "Fintech", "Education"], "Almost every modern web experience runs on it, so we can build exactly the behaviour you need."),
  "React.js": t("Front-end", "Component-based interfaces for fast web apps.", ["Single-page web applications", "Admin panels and dashboards", "Fast storefronts and portals"], ["SaaS", "E-commerce", "Healthcare portals"], "Reusable components keep a large product consistent and quick to change."),
  "Vue.js": t("Front-end", "A light, friendly framework for interactive front ends.", ["Booking and listing interfaces", "Progressive web apps", "Interactive parts inside existing sites"], ["Real estate", "Travel", "Education"], "It is quick to learn and quick to build with, which keeps projects simple and maintainable."),
  Angular: t("Front-end", "A complete framework for large business applications.", ["Enterprise web applications", "Data-heavy dashboards", "Role-based business portals"], ["Finance", "Healthcare", "Logistics"], "Its strict structure suits big teams and long-living products."),

  // ---- back end
  "Node.js": t("Back-end", "JavaScript on the server, built for real-time work.", ["Real-time apps such as chat and live tracking", "Fast REST and GraphQL APIs", "Back ends for web and mobile apps"], ["Fintech", "Logistics", "E-commerce"], "One language across front end and back end speeds up delivery and keeps the code consistent."),
  "Express.js": t("Back-end", "A lean toolkit for building APIs on Node.js.", ["APIs for mobile apps", "Login and user services", "Small, focused microservices"], ["Startups", "Retail", "Education"], "It stays out of the way, so APIs are simple, fast and easy to extend."),
  Laravel: t("Back-end", "A PHP framework for secure, well-organised web products.", ["Custom web portals and CMS", "E-commerce and booking systems", "CRM and ERP back ends"], ["Real estate", "Healthcare", "Education"], "Security, logins, queues and admin tools come ready, so we spend the time on your features."),
  Django: t("Back-end", "A Python framework for secure, data-driven sites.", ["Data-driven web applications", "Platforms with a powerful admin", "Sites that use machine learning"], ["Finance", "Healthcare", "Media"], "It is secure by default and a good fit when the product works with a lot of data."),
  Python: t("AI & data", "The language of data, automation and AI.", ["AI assistants and chatbots", "Data analysis and reports", "Automation and back-end services"], ["Healthcare", "Finance", "Retail"], "A huge ecosystem of data and AI libraries lets us go from idea to a working model quickly."),
  Flask: t("Back-end", "A small Python framework for focused services.", ["APIs that serve AI models", "Prototypes of data tools", "Dashboards for model results"], ["Healthcare", "Retail", "Research"], "It is light and flexible, perfect for putting a model or a tool behind a clean API."),

  // ---- databases
  MySQL: t("Databases", "A proven relational database for business data.", ["Product, order and customer data", "Booking and inventory systems", "Reporting for business apps"], ["E-commerce", "Education", "Retail"], "It is reliable, widely supported and fast for the everyday data of most business apps."),
  PostgreSQL: t("Databases", "A powerful database for complex, strict data.", ["Complex data with strict rules", "Analytics and location data", "Systems with many transactions"], ["Finance", "Logistics", "Real estate"], "It handles complicated queries and keeps data correct when the rules get demanding."),
  MongoDB: t("Databases", "A flexible database for data that changes shape.", ["Flexible content and catalogs", "Real-time app data", "Activity and event logs"], ["Media", "E-commerce", "IoT"], "It adapts easily when a product grows and the data does not fit fixed tables."),
  Firebase: t("Cloud & DevOps", "Ready-made back-end services for apps.", ["Real-time chat and syncing", "Login and push notifications", "Fast MVPs without managing servers"], ["Startups", "Social apps", "Delivery"], "It gives a mobile app logins, a database and notifications from day one."),

  // ---- cloud and DevOps
  AWS: t("Cloud & DevOps", "Cloud hosting and services that scale with you.", ["Scalable hosting for web and apps", "File storage and delivery", "Secure production set-ups"], ["E-commerce", "Healthcare", "Media"], "It lets a product start small and grow without moving to something new."),
  "Google Cloud": t("Cloud & DevOps", "Cloud services with strong data and AI tools.", ["Apps that use data and AI services", "Scalable APIs", "Analytics pipelines"], ["Retail", "Media", "Education"], "Its data and AI services are a good base for smart features."),
  Azure: t("Cloud & DevOps", "Cloud services that fit Microsoft-based companies.", ["Business apps in a Microsoft environment", "Secure enterprise hosting", "Single sign-on for teams"], ["Enterprise", "Finance", "Healthcare"], "It plugs into the tools a company already uses for identity and security."),
  Docker: t("Cloud & DevOps", "Packages an app so it runs the same everywhere.", ["The same app on a laptop and on a server", "Easy deployments and updates", "Separate, isolated services"], ["SaaS", "Fintech", "Agencies"], "It removes the 'works on my machine' problem and makes releases predictable."),
  Git: t("Cloud & DevOps", "Version control for safe teamwork.", ["Safe collaboration of many developers", "Full history and easy roll-backs", "Code review before anything goes live"], ["Every project", "Agencies", "SaaS"], "Every change is tracked, so nothing is lost and mistakes are easy to undo."),
  "CI/CD Pipelines": t("Cloud & DevOps", "Automatic tests and releases for every change.", ["Automatic tests on every change", "One-click releases", "Fewer surprises on release day"], ["SaaS", "Fintech", "E-commerce"], "Quality checks run by themselves, so releases are calmer and faster."),

  // ---- APIs and integrations
  "RESTful APIs": t("APIs & integrations", "The common language between apps and servers.", ["Apps that talk to your back end", "Connections to payment and delivery services", "Public APIs for partners"], ["E-commerce", "Fintech", "Logistics"], "Clean APIs make it simple to connect new apps and services later."),
  GraphQL: t("APIs & integrations", "Ask for exactly the data a screen needs.", ["Fast mobile screens with less data", "One API for web and app", "Flexible dashboards"], ["Media", "E-commerce", "SaaS"], "It cuts needless data transfer, which keeps apps quick even on slower networks."),
  "REST & GraphQL APIs": t("APIs & integrations", "The connections between your systems.", ["Links between CRM, website and apps", "Data syncing with other tools", "Partner and customer integrations"], ["Sales teams", "Logistics", "Services"], "Good APIs mean your tools share one source of data instead of copying it by hand."),
  Zapier: t("APIs & integrations", "No-code automation between hundreds of apps.", ["New lead to CRM to email, automatically", "Notifications in chat tools", "Simple workflows without custom code"], ["Small businesses", "Agencies", "Services"], "Small automations save hours of repeated work without a big build."),
  "HubSpot APIs": t("APIs & integrations", "Connect your own systems to HubSpot.", ["Website forms that create HubSpot contacts", "Two-way syncing of deals and customers", "Custom reports from CRM data"], ["B2B services", "SaaS", "Education"], "It keeps your marketing and sales data in one place, whatever systems you use."),

  // ---- mobile
  Flutter: t("Mobile", "One codebase for Android and iOS, with rich visuals.", ["Apps for Android and iOS from one code", "Polished, animated interfaces", "MVPs and full products"], ["Startups", "Retail", "Health and fitness"], "It gives a native feel on both platforms and keeps the cost and the time down."),
  "React Native": t("Mobile", "Mobile apps with React, for Android and iOS.", ["Cross-platform apps", "Apps that share logic with a web app", "Fast first versions"], ["E-commerce", "Social apps", "Services"], "Teams that already use React can move fast and share code between web and mobile."),
  Kotlin: t("Mobile", "The modern language for native Android apps.", ["Native Android apps", "Apps that use the camera, GPS and sensors", "High-performance features"], ["Delivery", "Fintech", "Health"], "Native code gives the best speed and full access to every Android feature."),
  Swift: t("Mobile", "The language for native iPhone and iPad apps.", ["Native iOS apps", "Apps tuned for Apple devices", "Apps ready for App Store review"], ["Fintech", "Health", "Lifestyle"], "It feels at home on Apple devices and follows the App Store guidelines closely."),

  // ---- design
  Figma: t("Design", "Collaborative interface design in the browser.", ["Website and app designs", "Clickable prototypes", "Shared design systems"], ["Every industry", "SaaS", "E-commerce"], "Designers, developers and clients work in the same file and give feedback live."),
  "Adobe XD": t("Design", "Design and prototyping for screens.", ["App and website screens", "Interactive prototypes", "Design hand-offs"], ["Startups", "Agencies", "Services"], "It makes it quick to turn an idea into a screen flow people can click."),
  Sketch: t("Design", "A focused tool for interface design.", ["Interface designs", "Icon sets", "Reusable symbols and styles"], ["Startups", "Agencies", "SaaS"], "Clean vector tools and reusable symbols keep large designs organised."),
  InVision: t("Design", "Prototypes and feedback in one place.", ["Clickable prototypes for review", "Design feedback with comments", "Walk-throughs for clients"], ["Agencies", "Startups", "Services"], "Clients can click through the design and comment right on the screen."),
  Zeplin: t("Design", "The bridge between design and development.", ["Specs for developers", "Shared colours, sizes and assets", "Design systems that stay in sync"], ["SaaS", "Agencies", "E-commerce"], "Developers get exact measurements and assets, so the build matches the design."),
  "Adobe Illustrator": t("Design", "Vector graphics that stay sharp at any size.", ["Logos and brand marks", "Icons and illustrations", "Print and packaging artwork"], ["Branding", "Retail", "Hospitality"], "Vector artwork can be scaled from a favicon to a billboard without losing quality."),
  "Adobe Photoshop": t("Design", "Image editing and creative compositions.", ["Social and ad creatives", "Photo retouching and mockups", "Web and banner graphics"], ["Retail", "Fashion", "Marketing"], "It is the standard for photo work and rich, layered visuals."),
  Photoshop: t("Design", "Image editing and creative compositions.", ["Social and ad creatives", "Photo retouching and mockups", "Web and banner graphics"], ["Retail", "Fashion", "Marketing"], "It is the standard for photo work and rich, layered visuals."),
  InDesign: t("Design", "Page layout for print and digital documents.", ["Brochures and catalogs", "Company profiles and reports", "Pitch and sales documents"], ["Corporate", "Education", "Real estate"], "It handles long, multi-page documents with consistent styles."),
  Canva: t("Design", "Quick, editable templates for everyday content.", ["Social media posts", "Simple presentations", "Templates your team can edit"], ["Small businesses", "Marketing teams", "Education"], "It lets your own team keep content fresh without waiting for a designer."),
  "UI Design": t("Design practice", "How the product looks and feels on screen.", ["Website and app interfaces", "Design systems", "Marketing pages"], ["Every industry", "SaaS", "E-commerce"], "Good interface design makes a product clear, trustworthy and pleasant to use."),
  Prototyping: t("Design practice", "A clickable version of the idea before it is built.", ["Interactive app and website flows", "Tested ideas before development", "Demos for investors and clients"], ["Startups", "SaaS", "Services"], "Problems are found and fixed in the prototype, where changes are cheap."),
  "UX Research": t("Design practice", "Learning what people really need.", ["User interviews and surveys", "Competitor and journey analysis", "A clear direction for the design"], ["Every industry", "Healthcare", "Education"], "Decisions based on real users beat guesses, and they are easy to explain."),
  "Animation & Interaction": t("Design practice", "Motion that explains and delights.", ["Hover and loading effects", "Smooth page and screen transitions", "Guided product tours"], ["SaaS", "E-commerce", "Media"], "Subtle motion tells people what is happening and makes a product feel alive."),

  // ---- motion and 3D
  "Adobe After Effects": t("Motion & 3D", "Motion graphics and visual effects.", ["Explainer and promo videos", "Animated logos and titles", "Social media motion content"], ["Marketing", "Education", "Media"], "It is the industry tool for turning flat designs into smooth, polished motion."),
  "After Effects": t("Motion & 3D", "Motion graphics and visual effects.", ["Explainer and promo videos", "Animated logos and titles", "Social media motion content"], ["Marketing", "Education", "Media"], "It is the industry tool for turning flat designs into smooth, polished motion."),
  Blender: t("Motion & 3D", "Free, powerful 3D modeling and animation.", ["Product models and visualizations", "3D animations", "Assets for games and the metaverse"], ["Retail", "Real estate", "Entertainment"], "A complete 3D pipeline in one tool, from modeling to final render."),
  "Cinema 4D": t("Motion & 3D", "3D for motion design and fast, polished results.", ["Motion graphics in 3D", "Product animations", "Abstract brand visuals"], ["Advertising", "Media", "Consumer products"], "It is quick to work in and blends well with After Effects."),
  "Autodesk Maya": t("Motion & 3D", "Professional 3D animation and character work.", ["Character animation", "Cinematic 3D scenes", "Detailed models and rigs"], ["Entertainment", "Gaming", "Advertising"], "It is built for complex animation, from characters to full scenes."),
  "Autodesk 3ds Max": t("Motion & 3D", "3D modeling and visualization.", ["Architectural and interior visuals", "Product models", "Detailed environments"], ["Real estate", "Architecture", "Furniture"], "Strong modeling and rendering tools for realistic, detailed visualizations."),

  // ---- immersive
  Unity: t("Immersive (XR)", "The engine behind games and immersive apps.", ["3D games and simulations", "AR and VR experiences", "Interactive product showrooms"], ["Gaming", "Education", "Retail"], "One engine for phones, desktops and headsets, with a huge toolbox of ready parts."),
  "Unreal Engine": t("Immersive (XR)", "Cinematic real-time 3D.", ["Highly realistic virtual worlds", "Virtual production and showrooms", "High-end games"], ["Gaming", "Automotive", "Real estate"], "It gives film-quality visuals in real time."),
  WebGL: t("Immersive (XR)", "3D graphics right inside the browser.", ["3D product viewers", "Interactive visual stories", "Browser games"], ["E-commerce", "Marketing", "Education"], "People see the 3D experience at once, with nothing to install."),
  "Three.js": t("Immersive (XR)", "A friendly toolkit for 3D on the web.", ["3D websites and scenes", "Product configurators", "Data visualizations in 3D"], ["Retail", "Marketing", "Real estate"], "It turns complex WebGL into something fast to build with and easy to tune."),
  WebXR: t("Immersive (XR)", "AR and VR in the browser.", ["Try-it-in-your-room experiences", "VR tours in a browser", "Immersive web demos"], ["Real estate", "Retail", "Education"], "Visitors step into AR or VR from a link, without an app."),
  "A-Frame": t("Immersive (XR)", "Quick VR scenes with simple markup.", ["VR scenes and prototypes", "360 degree tours", "Simple virtual spaces"], ["Education", "Tourism", "Real estate"], "It makes it fast to prototype and share a VR idea."),
  "Spatial.io": t("Immersive (XR)", "Shared virtual spaces for events and showcases.", ["Virtual galleries and showrooms", "Branded event spaces", "Social meet-ups in 3D"], ["Brands", "Events", "Art"], "A quick way to host people in a branded 3D space."),
  "Mozilla Hubs": t("Immersive (XR)", "Open-source social VR rooms.", ["Virtual meeting rooms", "Custom 3D rooms for communities", "Small events"], ["Education", "Communities", "Training"], "People can join from a browser, and the rooms can be customised."),
  "Decentraland SDK": t("Immersive (XR)", "Build experiences inside Decentraland.", ["Virtual stores and galleries", "Branded games and events", "Interactive scenes"], ["Brands", "Entertainment", "Art"], "It reaches an existing audience that already lives in the virtual world."),

  // ---- blockchain
  Ethereum: t("Blockchain", "A leading blockchain for digital assets and contracts.", ["NFT collections and marketplaces", "Smart contracts", "Wallet-connected apps"], ["Art", "Gaming", "Collectibles"], "A large, well-tested network with strong tools for digital ownership."),
  "Polygon Blockchain": t("Blockchain", "Lower-cost, faster transactions on Ethereum.", ["NFT marketplaces", "Wallet-based loyalty apps", "In-game assets"], ["Gaming", "Brands", "Art"], "Everyday users can take part without high transaction fees."),
  IPFS: t("Blockchain", "Decentralised storage for files.", ["Storage for NFT images and data", "Permanent, verifiable files", "Shared media libraries"], ["Art", "Collectibles", "Media"], "Files are addressed by what they are, so they cannot be silently changed."),
  "NFT.Storage": t("Blockchain", "Free, reliable storage for NFT data.", ["Hosting NFT media and metadata", "Backups of digital assets", "Collections that last"], ["Art", "Gaming", "Brands"], "It keeps the files behind an NFT available long term."),

  // ---- SEO
  "Google Search": t("SEO tools", "How people find you, straight from the source.", ["Search performance reports", "Fixes for indexing problems", "Insight into what people search"], ["Every industry", "Local business", "E-commerce"], "It shows how Google really sees your website."),
  Ahrefs: t("SEO tools", "Backlinks, keywords and competitor research.", ["Keyword and content ideas", "Backlink audits", "Competitor gap analysis"], ["E-commerce", "Services", "Publishers"], "Deep data shows where competitors win and where you can catch up."),
  SEMrush: t("SEO tools", "An all-in-one toolkit for search visibility.", ["Keyword research", "Site health audits", "Competitor tracking"], ["Retail", "Services", "B2B"], "One place to plan, track and report on search work."),
  "Screaming Frog": t("SEO tools", "A crawler that finds technical problems.", ["Broken links and redirects", "Missing titles and descriptions", "Site structure maps"], ["Large sites", "E-commerce", "Publishers"], "It crawls a site like a search engine and lists every issue."),
  "Yoast SEO": t("SEO tools", "On-page SEO help inside WordPress.", ["Page titles and descriptions", "Readable, well-structured content", "Sitemaps and structured data"], ["Blogs", "Small businesses", "Publishers"], "Your team gets clear guidance while writing, with no code needed."),
  Moz: t("SEO tools", "Authority, keywords and local listings.", ["Domain authority tracking", "Keyword research", "Local listing checks"], ["Local business", "Services", "Retail"], "Easy, readable metrics for tracking progress over time."),
  GTmetrix: t("SEO tools", "Page speed and performance reports.", ["Speed and Core Web Vitals checks", "Performance waterfalls", "Before and after comparisons"], ["E-commerce", "Publishers", "Every site"], "Fast pages rank better and convert better, and this shows exactly what slows them down."),

  // ---- AI and data
  TensorFlow: t("AI & data", "A framework for building and running models.", ["Image recognition", "Recommendation systems", "Models that run on phones and servers"], ["Healthcare", "Retail", "Manufacturing"], "A mature toolkit from research to production."),
  PyTorch: t("AI & data", "A flexible framework for deep learning.", ["Language and vision models", "Custom neural networks", "Fast experiments"], ["Healthcare", "Media", "Research"], "It is easy to experiment with, which shortens the road to a working model."),
  OpenAI: t("AI & data", "Language and image models you can build on.", ["Chatbots and AI assistants", "Content and summary tools", "Search over your own documents"], ["Support", "Education", "Legal"], "Strong ready-made models mean useful AI features without training from zero."),
  "Scikit-learn": t("AI & data", "Classic machine learning, made simple.", ["Predictions from business data", "Customer grouping", "Anomaly and fraud checks"], ["Finance", "Retail", "Telecom"], "Dependable, well-understood methods that often solve the problem without heavy models."),
  "Google Cloud AI": t("AI & data", "Managed AI services on Google Cloud.", ["Speech and vision features", "Translation and text analysis", "Model hosting at scale"], ["Retail", "Media", "Healthcare"], "Ready-made AI services speed up building and scaling."),
  "AWS AI": t("AI & data", "Managed AI services on AWS.", ["Document and image analysis", "Chatbots and voice", "Model training and hosting"], ["Healthcare", "Finance", "Retail"], "It sits next to the rest of your AWS set-up, which keeps things simple."),
  "Azure AI": t("AI & data", "Managed AI services on Microsoft Azure.", ["Document and language understanding", "Vision and speech features", "AI inside Microsoft-based tools"], ["Enterprise", "Finance", "Healthcare"], "A good match for companies already working in the Microsoft world."),
  Pandas: t("AI & data", "Data wrangling for analysis.", ["Cleaning and combining data", "Reports and summaries", "Data prepared for models"], ["Finance", "Retail", "Research"], "It turns messy tables into data you can trust."),
  NumPy: t("AI & data", "Fast numbers for science and AI.", ["Numeric computing", "The base of data and AI libraries", "Fast calculations on large arrays"], ["Research", "Finance", "Engineering"], "Almost every Python data tool is built on it."),

  // ---- brand and productivity
  "Google Fonts": t("Brand & productivity", "Free, fast-loading fonts for the web.", ["Brand typography on websites", "Readable text on every screen", "Consistent type in documents"], ["Every industry", "Publishers", "Startups"], "A wide choice of fonts that load quickly and work everywhere."),
  Typekit: t("Brand & productivity", "Professional fonts from Adobe.", ["Brand typefaces on web and print", "Premium type for logos", "Consistent type across tools"], ["Branding", "Publishers", "Corporate"], "Premium typefaces keep a brand looking distinctive and polished."),
  Notion: t("Brand & productivity", "Docs, notes and project planning together.", ["Brand guideline hubs", "Project plans and checklists", "Shared team knowledge"], ["Agencies", "Startups", "Teams"], "Everything about the project lives in one clear place."),
  Miro: t("Brand & productivity", "An online whiteboard for ideas.", ["Brand and strategy workshops", "Journey maps and flows", "Brainstorming boards"], ["Agencies", "Startups", "Product teams"], "Teams think out loud together, even when apart."),
  Loom: t("Brand & productivity", "Quick video messages.", ["Walk-throughs of designs", "Feedback on drafts", "Short training videos"], ["Agencies", "Remote teams", "Services"], "A two-minute video often replaces a long meeting."),
  Pitch: t("Brand & productivity", "Modern presentation design.", ["Investor decks", "Sales and client presentations", "Team updates"], ["Startups", "Services", "Corporate"], "Beautiful, consistent presentations that are easy to edit as a team."),
};

const ALIASES: Record<string, string> = { React: "React.js", "Adobe Photoshop": "Adobe Photoshop", "Adobe InDesign": "InDesign" };

/** The detail of a technology by its name (a few other spellings are understood). */
export const techDetail = (name: string): TechDetail | undefined => TECH_DETAILS[name] ?? TECH_DETAILS[ALIASES[name] ?? ""];
